/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type DagVoteStruct = {
  id: AddressLike;
  weight: BigNumberish;
  dist: BigNumberish;
  posInOther: BigNumberish;
};

export type DagVoteStructOutput = [
  id: string,
  weight: bigint,
  dist: bigint,
  posInOther: bigint
] & { id: string; weight: bigint; dist: bigint; posInOther: bigint };

export interface AnthillInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_REL_ROOT_DEPTH"
      | "addDagVote"
      | "balanceOf"
      | "calculateReputation"
      | "calculateReputationIterative"
      | "calculatedReputationForEpoch"
      | "changeName"
      | "decimalPoint"
      | "decimals"
      | "findDistAtSameDepth"
      | "findDistances"
      | "findDistancesRecNotLower"
      | "findNthParent"
      | "findRecDagVote"
      | "findRecDagVoteNew"
      | "findRelDepth"
      | "findRelDepthInner"
      | "findRelRoot"
      | "findSentDagVote"
      | "findSentDagVoteNew"
      | "joinTree"
      | "joinTreeAsRoot"
      | "leaveTree"
      | "lockTree"
      | "moveTreeVote"
      | "name"
      | "nameOf"
      | "readDepth"
      | "readRecDagVote"
      | "readSentDagVote"
      | "recDagVote"
      | "recDagVoteCount"
      | "recTreeVote"
      | "recTreeVoteCount"
      | "removeDagVote"
      | "reputation"
      | "reputationEpoch"
      | "root"
      | "sentDagVote"
      | "sentDagVoteCount"
      | "sentDagVoteTotalWeight"
      | "sentTreeVote"
      | "switchPositionWithParent"
      | "symbol"
      | "tokenName"
      | "tokenSymbol"
      | "unlocked"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddDagVoteEvent"
      | "ChangeNameEvent"
      | "JoinTreeEvent"
      | "LeaveTreeEvent"
      | "MoveTreeVoteEvent"
      | "RemoveDagVoteEvent"
      | "SwitchPositionWithParentEvent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_REL_ROOT_DEPTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDagVote",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateReputationIterative",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatedReputationForEpoch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeName",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "decimalPoint",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "findDistAtSameDepth",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findDistances",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findDistancesRecNotLower",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findNthParent",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "findRecDagVote",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findRecDagVoteNew",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findRelDepth",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findRelDepthInner",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findRelRoot",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findSentDagVote",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findSentDagVoteNew",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinTree",
    values: [AddressLike, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinTreeAsRoot",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "leaveTree",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lockTree", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "moveTreeVote",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "nameOf", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "readDepth",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "readRecDagVote",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "readSentDagVote",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recDagVote",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recDagVoteCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recTreeVote",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recTreeVoteCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDagVote",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reputationEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "root", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sentDagVote",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sentDagVoteCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sentDagVoteTotalWeight",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sentTreeVote",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "switchPositionWithParent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenSymbol",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unlocked", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_REL_ROOT_DEPTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addDagVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateReputationIterative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatedReputationForEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changeName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decimalPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "findDistAtSameDepth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findDistances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findDistancesRecNotLower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findNthParent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findRecDagVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findRecDagVoteNew",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findRelDepth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findRelDepthInner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findRelRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findSentDagVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findSentDagVoteNew",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinTree", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "joinTreeAsRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "leaveTree", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockTree", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "moveTreeVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nameOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "readDepth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "readRecDagVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readSentDagVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recDagVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recDagVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recTreeVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recTreeVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDagVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reputationEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "root", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sentDagVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sentDagVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sentDagVoteTotalWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sentTreeVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "switchPositionWithParent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenSymbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlocked", data: BytesLike): Result;
}

export namespace AddDagVoteEventEvent {
  export type InputTuple = [
    voter: AddressLike,
    recipient: AddressLike,
    weight: BigNumberish
  ];
  export type OutputTuple = [voter: string, recipient: string, weight: bigint];
  export interface OutputObject {
    voter: string;
    recipient: string;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChangeNameEventEvent {
  export type InputTuple = [voter: AddressLike, newName: string];
  export type OutputTuple = [voter: string, newName: string];
  export interface OutputObject {
    voter: string;
    newName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JoinTreeEventEvent {
  export type InputTuple = [
    voter: AddressLike,
    name: string,
    recipient: AddressLike
  ];
  export type OutputTuple = [voter: string, name: string, recipient: string];
  export interface OutputObject {
    voter: string;
    name: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaveTreeEventEvent {
  export type InputTuple = [voter: AddressLike];
  export type OutputTuple = [voter: string];
  export interface OutputObject {
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoveTreeVoteEventEvent {
  export type InputTuple = [voter: AddressLike, recipient: AddressLike];
  export type OutputTuple = [voter: string, recipient: string];
  export interface OutputObject {
    voter: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoveDagVoteEventEvent {
  export type InputTuple = [voter: AddressLike, recipient: AddressLike];
  export type OutputTuple = [voter: string, recipient: string];
  export interface OutputObject {
    voter: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwitchPositionWithParentEventEvent {
  export type InputTuple = [voter: AddressLike];
  export type OutputTuple = [voter: string];
  export interface OutputObject {
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Anthill extends BaseContract {
  connect(runner?: ContractRunner | null): Anthill;
  waitForDeployment(): Promise<this>;

  interface: AnthillInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_REL_ROOT_DEPTH: TypedContractMethod<[], [bigint], "view">;

  addDagVote: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike, weight: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[voter: AddressLike], [bigint], "view">;

  calculateReputation: TypedContractMethod<
    [voter: AddressLike],
    [bigint],
    "nonpayable"
  >;

  calculateReputationIterative: TypedContractMethod<
    [voter: AddressLike],
    [void],
    "nonpayable"
  >;

  calculatedReputationForEpoch: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  changeName: TypedContractMethod<
    [voter: AddressLike, voterName: string],
    [void],
    "nonpayable"
  >;

  decimalPoint: TypedContractMethod<[], [bigint], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  findDistAtSameDepth: TypedContractMethod<
    [add1: AddressLike, add2: AddressLike],
    [[boolean, bigint] & { isSameDepth: boolean; distance: bigint }],
    "view"
  >;

  findDistances: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, bigint, bigint] & {
        isLocalEitherWay: boolean;
        sDist: bigint;
        rDist: bigint;
      }
    ],
    "view"
  >;

  findDistancesRecNotLower: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, bigint, bigint] & {
        isLocal: boolean;
        sDist: bigint;
        rDist: bigint;
      }
    ],
    "view"
  >;

  findNthParent: TypedContractMethod<
    [voter: AddressLike, height: BigNumberish],
    [string],
    "view"
  >;

  findRecDagVote: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, DagVoteStructOutput] & {
        votable: boolean;
        voted: boolean;
        sdist: bigint;
        depth: bigint;
        votePos: bigint;
        dagVote: DagVoteStructOutput;
      }
    ],
    "view"
  >;

  findRecDagVoteNew: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, boolean, bigint, DagVoteStructOutput] & {
        votable: boolean;
        voted: boolean;
        votePos: bigint;
        dagVote: DagVoteStructOutput;
      }
    ],
    "view"
  >;

  findRelDepth: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [[boolean, bigint] & { isLocal: boolean; relDepth: bigint }],
    "view"
  >;

  findRelDepthInner: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, bigint, bigint] & {
        isLocal: boolean;
        sRelRootDiff: bigint;
        rRelRootDiff: bigint;
      }
    ],
    "view"
  >;

  findRelRoot: TypedContractMethod<
    [voter: AddressLike],
    [[string, bigint] & { relRoot: string; relDepth: bigint }],
    "view"
  >;

  findSentDagVote: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, DagVoteStructOutput] & {
        votable: boolean;
        voted: boolean;
        sDist: bigint;
        rDist: bigint;
        votePos: bigint;
        dagVote: DagVoteStructOutput;
      }
    ],
    "view"
  >;

  findSentDagVoteNew: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, boolean, bigint, DagVoteStructOutput] & {
        votable: boolean;
        voted: boolean;
        votePos: bigint;
        dagVote: DagVoteStructOutput;
      }
    ],
    "view"
  >;

  joinTree: TypedContractMethod<
    [voter: AddressLike, voterName: string, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  joinTreeAsRoot: TypedContractMethod<
    [voter: AddressLike, voterName: string],
    [void],
    "nonpayable"
  >;

  leaveTree: TypedContractMethod<[voter: AddressLike], [void], "nonpayable">;

  lockTree: TypedContractMethod<[], [void], "nonpayable">;

  moveTreeVote: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nameOf: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  readDepth: TypedContractMethod<[voter: AddressLike], [bigint], "view">;

  readRecDagVote: TypedContractMethod<
    [recipient: AddressLike, votePos: BigNumberish],
    [DagVoteStructOutput],
    "view"
  >;

  readSentDagVote: TypedContractMethod<
    [voter: AddressLike, votePos: BigNumberish],
    [DagVoteStructOutput],
    "view"
  >;

  recDagVote: TypedContractMethod<
    [voter: AddressLike, counter: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        id: string;
        weight: bigint;
        dist: bigint;
        posInOther: bigint;
      }
    ],
    "view"
  >;

  recDagVoteCount: TypedContractMethod<[voter: AddressLike], [bigint], "view">;

  recTreeVote: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  recTreeVoteCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  removeDagVote: TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  reputation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  reputationEpoch: TypedContractMethod<[], [bigint], "view">;

  root: TypedContractMethod<[], [string], "view">;

  sentDagVote: TypedContractMethod<
    [voter: AddressLike, counter: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        id: string;
        weight: bigint;
        dist: bigint;
        posInOther: bigint;
      }
    ],
    "view"
  >;

  sentDagVoteCount: TypedContractMethod<[voter: AddressLike], [bigint], "view">;

  sentDagVoteTotalWeight: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  sentTreeVote: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  switchPositionWithParent: TypedContractMethod<
    [voter: AddressLike],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenName: TypedContractMethod<[], [string], "view">;

  tokenSymbol: TypedContractMethod<[], [string], "view">;

  unlocked: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_REL_ROOT_DEPTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addDagVote"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike, weight: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[voter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateReputation"
  ): TypedContractMethod<[voter: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateReputationIterative"
  ): TypedContractMethod<[voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculatedReputationForEpoch"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "changeName"
  ): TypedContractMethod<
    [voter: AddressLike, voterName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decimalPoint"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "findDistAtSameDepth"
  ): TypedContractMethod<
    [add1: AddressLike, add2: AddressLike],
    [[boolean, bigint] & { isSameDepth: boolean; distance: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "findDistances"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, bigint, bigint] & {
        isLocalEitherWay: boolean;
        sDist: bigint;
        rDist: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "findDistancesRecNotLower"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, bigint, bigint] & {
        isLocal: boolean;
        sDist: bigint;
        rDist: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "findNthParent"
  ): TypedContractMethod<
    [voter: AddressLike, height: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "findRecDagVote"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, DagVoteStructOutput] & {
        votable: boolean;
        voted: boolean;
        sdist: bigint;
        depth: bigint;
        votePos: bigint;
        dagVote: DagVoteStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "findRecDagVoteNew"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, boolean, bigint, DagVoteStructOutput] & {
        votable: boolean;
        voted: boolean;
        votePos: bigint;
        dagVote: DagVoteStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "findRelDepth"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [[boolean, bigint] & { isLocal: boolean; relDepth: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "findRelDepthInner"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, bigint, bigint] & {
        isLocal: boolean;
        sRelRootDiff: bigint;
        rRelRootDiff: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "findRelRoot"
  ): TypedContractMethod<
    [voter: AddressLike],
    [[string, bigint] & { relRoot: string; relDepth: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "findSentDagVote"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, DagVoteStructOutput] & {
        votable: boolean;
        voted: boolean;
        sDist: bigint;
        rDist: bigint;
        votePos: bigint;
        dagVote: DagVoteStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "findSentDagVoteNew"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [
      [boolean, boolean, bigint, DagVoteStructOutput] & {
        votable: boolean;
        voted: boolean;
        votePos: bigint;
        dagVote: DagVoteStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinTree"
  ): TypedContractMethod<
    [voter: AddressLike, voterName: string, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "joinTreeAsRoot"
  ): TypedContractMethod<
    [voter: AddressLike, voterName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "leaveTree"
  ): TypedContractMethod<[voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lockTree"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "moveTreeVote"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nameOf"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "readDepth"
  ): TypedContractMethod<[voter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "readRecDagVote"
  ): TypedContractMethod<
    [recipient: AddressLike, votePos: BigNumberish],
    [DagVoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "readSentDagVote"
  ): TypedContractMethod<
    [voter: AddressLike, votePos: BigNumberish],
    [DagVoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "recDagVote"
  ): TypedContractMethod<
    [voter: AddressLike, counter: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        id: string;
        weight: bigint;
        dist: bigint;
        posInOther: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recDagVoteCount"
  ): TypedContractMethod<[voter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recTreeVote"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "recTreeVoteCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeDagVote"
  ): TypedContractMethod<
    [voter: AddressLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "reputationEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "root"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sentDagVote"
  ): TypedContractMethod<
    [voter: AddressLike, counter: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        id: string;
        weight: bigint;
        dist: bigint;
        posInOther: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sentDagVoteCount"
  ): TypedContractMethod<[voter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sentDagVoteTotalWeight"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sentTreeVote"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "switchPositionWithParent"
  ): TypedContractMethod<[voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenSymbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unlocked"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "AddDagVoteEvent"
  ): TypedContractEvent<
    AddDagVoteEventEvent.InputTuple,
    AddDagVoteEventEvent.OutputTuple,
    AddDagVoteEventEvent.OutputObject
  >;
  getEvent(
    key: "ChangeNameEvent"
  ): TypedContractEvent<
    ChangeNameEventEvent.InputTuple,
    ChangeNameEventEvent.OutputTuple,
    ChangeNameEventEvent.OutputObject
  >;
  getEvent(
    key: "JoinTreeEvent"
  ): TypedContractEvent<
    JoinTreeEventEvent.InputTuple,
    JoinTreeEventEvent.OutputTuple,
    JoinTreeEventEvent.OutputObject
  >;
  getEvent(
    key: "LeaveTreeEvent"
  ): TypedContractEvent<
    LeaveTreeEventEvent.InputTuple,
    LeaveTreeEventEvent.OutputTuple,
    LeaveTreeEventEvent.OutputObject
  >;
  getEvent(
    key: "MoveTreeVoteEvent"
  ): TypedContractEvent<
    MoveTreeVoteEventEvent.InputTuple,
    MoveTreeVoteEventEvent.OutputTuple,
    MoveTreeVoteEventEvent.OutputObject
  >;
  getEvent(
    key: "RemoveDagVoteEvent"
  ): TypedContractEvent<
    RemoveDagVoteEventEvent.InputTuple,
    RemoveDagVoteEventEvent.OutputTuple,
    RemoveDagVoteEventEvent.OutputObject
  >;
  getEvent(
    key: "SwitchPositionWithParentEvent"
  ): TypedContractEvent<
    SwitchPositionWithParentEventEvent.InputTuple,
    SwitchPositionWithParentEventEvent.OutputTuple,
    SwitchPositionWithParentEventEvent.OutputObject
  >;

  filters: {
    "AddDagVoteEvent(address,address,uint256)": TypedContractEvent<
      AddDagVoteEventEvent.InputTuple,
      AddDagVoteEventEvent.OutputTuple,
      AddDagVoteEventEvent.OutputObject
    >;
    AddDagVoteEvent: TypedContractEvent<
      AddDagVoteEventEvent.InputTuple,
      AddDagVoteEventEvent.OutputTuple,
      AddDagVoteEventEvent.OutputObject
    >;

    "ChangeNameEvent(address,string)": TypedContractEvent<
      ChangeNameEventEvent.InputTuple,
      ChangeNameEventEvent.OutputTuple,
      ChangeNameEventEvent.OutputObject
    >;
    ChangeNameEvent: TypedContractEvent<
      ChangeNameEventEvent.InputTuple,
      ChangeNameEventEvent.OutputTuple,
      ChangeNameEventEvent.OutputObject
    >;

    "JoinTreeEvent(address,string,address)": TypedContractEvent<
      JoinTreeEventEvent.InputTuple,
      JoinTreeEventEvent.OutputTuple,
      JoinTreeEventEvent.OutputObject
    >;
    JoinTreeEvent: TypedContractEvent<
      JoinTreeEventEvent.InputTuple,
      JoinTreeEventEvent.OutputTuple,
      JoinTreeEventEvent.OutputObject
    >;

    "LeaveTreeEvent(address)": TypedContractEvent<
      LeaveTreeEventEvent.InputTuple,
      LeaveTreeEventEvent.OutputTuple,
      LeaveTreeEventEvent.OutputObject
    >;
    LeaveTreeEvent: TypedContractEvent<
      LeaveTreeEventEvent.InputTuple,
      LeaveTreeEventEvent.OutputTuple,
      LeaveTreeEventEvent.OutputObject
    >;

    "MoveTreeVoteEvent(address,address)": TypedContractEvent<
      MoveTreeVoteEventEvent.InputTuple,
      MoveTreeVoteEventEvent.OutputTuple,
      MoveTreeVoteEventEvent.OutputObject
    >;
    MoveTreeVoteEvent: TypedContractEvent<
      MoveTreeVoteEventEvent.InputTuple,
      MoveTreeVoteEventEvent.OutputTuple,
      MoveTreeVoteEventEvent.OutputObject
    >;

    "RemoveDagVoteEvent(address,address)": TypedContractEvent<
      RemoveDagVoteEventEvent.InputTuple,
      RemoveDagVoteEventEvent.OutputTuple,
      RemoveDagVoteEventEvent.OutputObject
    >;
    RemoveDagVoteEvent: TypedContractEvent<
      RemoveDagVoteEventEvent.InputTuple,
      RemoveDagVoteEventEvent.OutputTuple,
      RemoveDagVoteEventEvent.OutputObject
    >;

    "SwitchPositionWithParentEvent(address)": TypedContractEvent<
      SwitchPositionWithParentEventEvent.InputTuple,
      SwitchPositionWithParentEventEvent.OutputTuple,
      SwitchPositionWithParentEventEvent.OutputObject
    >;
    SwitchPositionWithParentEvent: TypedContractEvent<
      SwitchPositionWithParentEventEvent.InputTuple,
      SwitchPositionWithParentEventEvent.OutputTuple,
      SwitchPositionWithParentEventEvent.OutputObject
    >;
  };
}
