/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Anthill } from "./Anthill";
export * as factories from "./factories";
export { Anthill__factory } from "./factories/Anthill__factory";
